version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 16
    commands:
      - npm install -g
      - npm install --save-dev @angular-devkit/build-angular
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build
      - echo Build ended on `date`
artifacts:
  files:
    - "**/*"
  base-directory: "dist*"
