version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build
      - echo Build ended on `date`
artifacts:
  files:
    - "dist/my-blog-frontend/*"
