version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ng build
      - echo Build ended on `date`
artifacts:
  files:
    - "**/*"
  base-directory: "dist*"
